### ISSUE TITLE
code in readme is not valid Go

### ISSUE THREAD

**Issue by deanveloper** [mateuspontes/gophercss#2]
the readme was recently changed to use a `Style` struct rather than a `map[string]interface{}`, although the keys are still strings rather than struct fields. If you want to use a `Style` struct then the fields must be set with names such as `Margin` and `Padding` and without quotes

**Comment by mateuspontes** [comment]
we created `Style` as an alias to `type Style map[string]interface{}` inside css package. Thanks for correcting, I'll update the readme. :)
